name: 'CI'
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm test