name: 'CI'
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: lint
        run: pnpm check:ci
      - name: Test
        run: pnpm coverage
